Implement support for signature v4
jamhall/s3rver pull request #660
Opened 2020-08-15 15:02 UTC by idevelop

- Implement v4 signing algorithm, minor code changes necessary to extract relevant data from the request
- Fixed failing CORS OPTIONS request when using signed headers (I think OPTIONS should not be verified at all, since it's a different HTTP method so would definitely result in a different signature).
- Resolved small issue when calculating the canonical query string regarding params with no value (v2 does not require the = to be present, v4 does), so I moved that stripping code into the v2-specific code path
- Added unit tests for incorrect v4 signatures when using headers as well as using query params
- Confirmed locally that signed GET and PUT requests work correctly, including CORS, from my web app
- Confirmed locally that corrupting a signed URL results in a 403

Fixes #659

2020-08-24 13:20 UTC, idevelop commented
@kherock is this something you'd be interested in merging?

2021-02-11 04:16 UTC, fishcharlie requested changes

2021-02-11 04:16 UTC, fishcharlie commented on test/middleware/authentication.spec.js
> +  });
Seems like we should also have a test to verify that a successful signature actually works, right?

2021-02-11 04:16 UTC, fishcharlie commented on lib/middleware/authentication.js
> +function calculateSignatureV4(stringToSign, secretKey, date, region, service) {
Do we want to break out the V2 and V4 methods into 2 different files? That way it reduces the file size of this file, and we can separate out concerns a little bit?

2021-02-12 02:57 UTC, kherock commented
These just needs a couple more tests but otherwise this would be a great addition.

I did want to suggest that AWS signing is a problem that has already been solved and it might be a better use of this project's time to offload request signing to another library such as [aws4](https://www.npmjs.com/package/aws4).

2021-03-03 05:59 UTC, kherock commented
I've switched the default S3 client used in tests to use v4 signing. There were some slight tweaks I needed to make for computing the canonicalized query string for both versions. Thanks for finding the existing bug in the V2 signing as well!

2021-03-03 06:04 UTC, merged